# Generated by Django 5.1.3 on 2024-11-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('categoria', models.CharField(choices=[('bicicleta', 'Bicicleta'), ('peca', 'Peça'), ('acessorio', 'Acessório')], max_length=20, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Produto')),
            ],
        ),
    ]
