# Generated by Django 5.1.3 on 2024-11-26 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Disponível')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_produtos', to='estoque.produto')),
            ],
        ),
    ]
