# Generated by Django 5.1.3 on 2024-11-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_estoqueproduto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstoqueProduto',
        ),
    ]
