# Generated by Django 5.1.3 on 2024-12-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_delete_estoqueproduto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'permissions': [('adicionar_produto', 'Pode adicionar produto'), ('editar_produto', 'Pode editar produto'), ('remover_produto', 'Pode remover produto')]},
        ),
    ]
