# Generated by Django 5.1.3 on 2024-12-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
    ]
