# Generated by Django 5.1.3 on 2024-11-24 23:16

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('descricao_servico', models.TextField(verbose_name='Descrição do Serviço')),
                ('data', models.DateField(default=django.db.models.functions.datetime.Now, verbose_name='Data do Serviço')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Utilizada')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordens_servico.ordemservico')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
            options={
                'unique_together': {('produto', 'ordem_servico')},
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='produtos_usados',
            field=models.ManyToManyField(blank=True, through='ordens_servico.ProdutoOrdemServico', to='estoque.produto'),
        ),
    ]
