# Generated by Django 5.1.3 on 2024-11-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoordemservico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
