# Generated by Django 5.1.3 on 2024-11-25 03:02

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0002_produtoordemservico_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now, verbose_name='Data do Serviço'),
        ),
    ]
