# Generated by Django 5.1.3 on 2024-11-25 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0003_alter_ordemservico_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Serviço'),
        ),
    ]
