# Generated by Django 5.1.2 on 2024-11-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('ordens_servico', '0003_alter_ordemservico_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtoordemservico',
            old_name='ordem_servico',
            new_name='ordens_servico',
        ),
        migrations.AlterUniqueTogether(
            name='produtoordemservico',
            unique_together={('produto', 'ordens_servico')},
        ),
    ]
