# Generated by Django 5.1.3 on 2024-11-26 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_estoqueproduto'),
        ('ordens_servico', '0004_alter_ordemservico_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoordemservico',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico_produtos', to='estoque.produto'),
        ),
    ]
